export type Flag = {
  code: string;
  severity: "info" | "warn" | "bad";
  detail: string;
};

const AGENT_MARKERS = [
  /CURSOR_AGENT_PR_BODY/i,
  /<!--\s*cursor/i,
  /\bMade with Cursor\b/i,
  /\bGenerated by (GitHub )?Copilot\b/i,
];

const AGENT_TEMPLATES = [
  /\bH0\d\s+KEEP\b/,
  /\bH0\d\s+triage\b/,
  /^KEEP:\s/m,
  /^CHECK:\s/m,
  /^Collision:/m,
  /^Exact-head comment on /m,
];

const GENERIC_AI = [
  /\bAs an AI\b/i,
  /\bI('d| would) be happy to\b/i,
  /\bHope this helps!?\b/i,
  /\bLet me know if you (need|have) any (further )?(questions|help|clarification)/i,
  /\bHere('s| is) a comprehensive\b/i,
  /\bGreat question!?\b/i,
  /\bAbsolutely! I('d| can| will)\b/i,
  /\bI hope this (helps|answers)\b/i,
  /\bIn today's (fast-paced|digital)\b/i,
  /\bdelve into\b/i,
  /\bunleash( the)? potential\b/i,
  /\bIt('s| is) important to note that\b/i,
];

export function excerptOf(body: string | null | undefined, max = 500) {
  const text = (body ?? "").replace(/\s+/g, " ").trim();
  if (text.length <= max) return text;
  return `${text.slice(0, max)}…`;
}

export function flagContribution(input: {
  type: string;
  title?: string | null;
  body?: string | null;
}): Flag[] {
  const flags: Flag[] = [];
  const body = input.body ?? "";
  const title = (input.title ?? "").trim();
  const trimmed = body.trim();

  if (!trimmed) {
    flags.push({
      code: "empty_body",
      severity: input.type === "comment" ? "bad" : "warn",
      detail: "No body text",
    });
  } else if (trimmed.length < 12 && !/^([+-]1|lgtm|thanks!?|ty|done\.?)$/i.test(trimmed)) {
    flags.push({
      code: "very_short",
      severity: "info",
      detail: `Only ${trimmed.length} characters`,
    });
  }

  if (!title && (input.type === "issue" || input.type === "pull_request")) {
    flags.push({
      code: "empty_title",
      severity: "bad",
      detail: "Missing title",
    });
  }

  for (const re of AGENT_MARKERS) {
    if (re.test(body) || re.test(title)) {
      flags.push({
        code: "agent_marker",
        severity: "warn",
        detail: `Matched ${re.source}`,
      });
      break;
    }
  }

  for (const re of AGENT_TEMPLATES) {
    if (re.test(trimmed) || re.test(title)) {
      flags.push({
        code: "agent_template",
        severity: "warn",
        detail: `Matched ${re.source}`,
      });
      break;
    }
  }

  for (const re of GENERIC_AI) {
    if (re.test(trimmed)) {
      flags.push({
        code: "generic_ai_slop",
        severity: "bad",
        detail: `Matched ${re.source}`,
      });
      break;
    }
  }

  if (/^Claude\//i.test(title) || /cursor\/[a-z0-9-]+/i.test(title)) {
    flags.push({
      code: "machine_title",
      severity: "warn",
      detail: "Title looks like an agent session/branch name",
    });
  }

  if (
    /<!--\s*Provide a brief description/i.test(body) ||
    /Closes #\s*Related to #/.test(body)
  ) {
    flags.push({
      code: "unfilled_template",
      severity: "warn",
      detail: "PR body still has the empty template",
    });
  }

  if (/^(sure!?|absolutely!?|sounds good\.?|lgtm!?|\+1)$/i.test(trimmed)) {
    flags.push({
      code: "low_signal",
      severity: "info",
      detail: "Acknowledgement-only comment",
    });
  }

  const emojiOnly = trimmed.replace(/[\p{Emoji_Presentation}\p{Extended_Pictographic}\s]+/gu, "");
  if (trimmed.length > 0 && emojiOnly.length === 0) {
    flags.push({
      code: "emoji_only",
      severity: "info",
      detail: "Emoji-only body",
    });
  }

  return flags;
}

export function flagDuplicates(
  items: { id: string; excerpt: string }[],
): Map<string, Flag> {
  const out = new Map<string, Flag>();
  const buckets = new Map<string, string[]>();
  for (const item of items) {
    const key = item.excerpt.slice(0, 180).toLowerCase();
    if (key.length < 40) continue;
    const list = buckets.get(key) ?? [];
    list.push(item.id);
    buckets.set(key, list);
  }
  for (const [, ids] of buckets) {
    if (ids.length < 3) continue;
    for (const id of ids) {
      out.set(id, {
        code: "near_duplicate",
        severity: "warn",
        detail: `Same excerpt as ${ids.length} other items`,
      });
    }
  }
  return out;
}
